// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RamblerAcademyAPI.Data;

namespace RamblerAcademyAPI.Migrations
{
    [DbContext(typeof(RamblerAcademyContext))]
    [Migration("20200509181958_AbbreviationBuildingProperty")]
    partial class AbbreviationBuildingProperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("RamblerAcademyAPI.Models.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Building");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "MB",
                            Name = "Main Building"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "JA",
                            Name = "Johnson Arts Building"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = "WH",
                            Name = "Welch Humanities"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = "RS",
                            Name = "Rodney Sciences"
                        });
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.Classroom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("BuildingId")
                        .HasColumnType("integer");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<int>("HallwayNumber")
                        .HasColumnType("integer");

                    b.Property<int>("MaxCapacity")
                        .HasColumnType("integer");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("Floor", "HallwayNumber", "RoomNumber", "BuildingId")
                        .IsUnique();

                    b.ToTable("Classroom");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuildingId = 1,
                            Floor = 1,
                            HallwayNumber = 1,
                            MaxCapacity = 30,
                            RoomNumber = 12
                        },
                        new
                        {
                            Id = 2,
                            BuildingId = 1,
                            Floor = 1,
                            HallwayNumber = 1,
                            MaxCapacity = 30,
                            RoomNumber = 14
                        },
                        new
                        {
                            Id = 3,
                            BuildingId = 4,
                            Floor = 1,
                            HallwayNumber = 1,
                            MaxCapacity = 200,
                            RoomNumber = 10
                        },
                        new
                        {
                            Id = 4,
                            BuildingId = 4,
                            Floor = 1,
                            HallwayNumber = 1,
                            MaxCapacity = 200,
                            RoomNumber = 20
                        },
                        new
                        {
                            Id = 5,
                            BuildingId = 4,
                            Floor = 1,
                            HallwayNumber = 2,
                            MaxCapacity = 30,
                            RoomNumber = 32
                        },
                        new
                        {
                            Id = 6,
                            BuildingId = 4,
                            Floor = 1,
                            HallwayNumber = 2,
                            MaxCapacity = 30,
                            RoomNumber = 43
                        },
                        new
                        {
                            Id = 7,
                            BuildingId = 2,
                            Floor = 1,
                            HallwayNumber = 1,
                            MaxCapacity = 50,
                            RoomNumber = 2
                        },
                        new
                        {
                            Id = 8,
                            BuildingId = 2,
                            Floor = 1,
                            HallwayNumber = 1,
                            MaxCapacity = 50,
                            RoomNumber = 7
                        });
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("CourseNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("SubjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("SubjectId", "CourseNumber")
                        .IsUnique();

                    b.ToTable("Course");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseNumber = 10,
                            Name = "College Algebra",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 2,
                            CourseNumber = 100,
                            Name = "Pre-Calculus",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            CourseNumber = 400,
                            Name = "Calculus I",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 4,
                            CourseNumber = 250,
                            Name = "Summer Math Camp",
                            SubjectId = 1
                        },
                        new
                        {
                            Id = 5,
                            CourseNumber = 200,
                            Name = "Early Civilizations",
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 6,
                            CourseNumber = 500,
                            Name = "American History - Pre Civil War",
                            SubjectId = 2
                        },
                        new
                        {
                            Id = 7,
                            CourseNumber = 600,
                            Name = "American History - Post Civil War",
                            SubjectId = 2
                        });
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.CourseSection", b =>
                {
                    b.Property<int>("CourseReferenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("ClassroomId")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FinalExamDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SectionNumber")
                        .HasColumnType("integer");

                    b.Property<int>("SemesterId")
                        .HasColumnType("integer");

                    b.HasKey("CourseReferenceNumber");

                    b.HasIndex("ClassroomId");

                    b.HasIndex("SemesterId");

                    b.HasIndex("CourseId", "SectionNumber", "SemesterId")
                        .IsUnique();

                    b.ToTable("CourseSection");

                    b.HasData(
                        new
                        {
                            CourseReferenceNumber = 57494,
                            ClassroomId = 1,
                            CourseId = 1,
                            FinalExamDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionNumber = 1,
                            SemesterId = 1
                        },
                        new
                        {
                            CourseReferenceNumber = 59256,
                            ClassroomId = 2,
                            CourseId = 2,
                            FinalExamDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionNumber = 1,
                            SemesterId = 1
                        },
                        new
                        {
                            CourseReferenceNumber = 28539,
                            ClassroomId = 1,
                            CourseId = 4,
                            FinalExamDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionNumber = 1,
                            SemesterId = 1
                        },
                        new
                        {
                            CourseReferenceNumber = 78934,
                            ClassroomId = 7,
                            CourseId = 5,
                            FinalExamDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionNumber = 1,
                            SemesterId = 1
                        },
                        new
                        {
                            CourseReferenceNumber = 94583,
                            ClassroomId = 8,
                            CourseId = 6,
                            FinalExamDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SectionNumber = 1,
                            SemesterId = 1
                        });
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.CourseSectionDayTimeSlot", b =>
                {
                    b.Property<int>("CourseReferenceNumber")
                        .HasColumnType("integer");

                    b.Property<int>("DayId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("integer");

                    b.HasKey("CourseReferenceNumber", "DayId", "TimeSlotId");

                    b.HasIndex("DayId", "TimeSlotId");

                    b.ToTable("CourseSectionDayTimeSlot");

                    b.HasData(
                        new
                        {
                            CourseReferenceNumber = 57494,
                            DayId = 3,
                            TimeSlotId = 2
                        },
                        new
                        {
                            CourseReferenceNumber = 57494,
                            DayId = 5,
                            TimeSlotId = 2
                        },
                        new
                        {
                            CourseReferenceNumber = 59256,
                            DayId = 3,
                            TimeSlotId = 3
                        },
                        new
                        {
                            CourseReferenceNumber = 59256,
                            DayId = 5,
                            TimeSlotId = 3
                        },
                        new
                        {
                            CourseReferenceNumber = 78934,
                            DayId = 3,
                            TimeSlotId = 5
                        },
                        new
                        {
                            CourseReferenceNumber = 78934,
                            DayId = 5,
                            TimeSlotId = 5
                        },
                        new
                        {
                            CourseReferenceNumber = 94583,
                            DayId = 3,
                            TimeSlotId = 6
                        },
                        new
                        {
                            CourseReferenceNumber = 94583,
                            DayId = 5,
                            TimeSlotId = 6
                        });
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.Day", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<char>("Abbreviation")
                        .HasColumnType("character(1)");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Day");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = 'U',
                            Name = "Sunday"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = 'M',
                            Name = "Monday"
                        },
                        new
                        {
                            Id = 3,
                            Abbreviation = 'T',
                            Name = "Tuesday"
                        },
                        new
                        {
                            Id = 4,
                            Abbreviation = 'W',
                            Name = "Wednesday"
                        },
                        new
                        {
                            Id = 5,
                            Abbreviation = 'R',
                            Name = "Thursday"
                        },
                        new
                        {
                            Id = 6,
                            Abbreviation = 'F',
                            Name = "Friday"
                        },
                        new
                        {
                            Id = 7,
                            Abbreviation = 'S',
                            Name = "Saturday"
                        });
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.DayTimeSlot", b =>
                {
                    b.Property<int>("DayId")
                        .HasColumnType("integer");

                    b.Property<int>("TimeSlotId")
                        .HasColumnType("integer");

                    b.HasKey("DayId", "TimeSlotId");

                    b.HasIndex("TimeSlotId");

                    b.ToTable("DayTimeSlot");

                    b.HasData(
                        new
                        {
                            DayId = 3,
                            TimeSlotId = 1
                        },
                        new
                        {
                            DayId = 3,
                            TimeSlotId = 2
                        },
                        new
                        {
                            DayId = 3,
                            TimeSlotId = 3
                        },
                        new
                        {
                            DayId = 3,
                            TimeSlotId = 4
                        },
                        new
                        {
                            DayId = 3,
                            TimeSlotId = 5
                        },
                        new
                        {
                            DayId = 3,
                            TimeSlotId = 6
                        },
                        new
                        {
                            DayId = 3,
                            TimeSlotId = 7
                        },
                        new
                        {
                            DayId = 3,
                            TimeSlotId = 8
                        },
                        new
                        {
                            DayId = 5,
                            TimeSlotId = 1
                        },
                        new
                        {
                            DayId = 5,
                            TimeSlotId = 2
                        },
                        new
                        {
                            DayId = 5,
                            TimeSlotId = 3
                        },
                        new
                        {
                            DayId = 5,
                            TimeSlotId = 4
                        },
                        new
                        {
                            DayId = 5,
                            TimeSlotId = 5
                        },
                        new
                        {
                            DayId = 5,
                            TimeSlotId = 6
                        },
                        new
                        {
                            DayId = 5,
                            TimeSlotId = 7
                        },
                        new
                        {
                            DayId = 5,
                            TimeSlotId = 8
                        },
                        new
                        {
                            DayId = 2,
                            TimeSlotId = 9
                        },
                        new
                        {
                            DayId = 2,
                            TimeSlotId = 10
                        },
                        new
                        {
                            DayId = 2,
                            TimeSlotId = 11
                        },
                        new
                        {
                            DayId = 2,
                            TimeSlotId = 12
                        },
                        new
                        {
                            DayId = 2,
                            TimeSlotId = 13
                        },
                        new
                        {
                            DayId = 2,
                            TimeSlotId = 14
                        },
                        new
                        {
                            DayId = 2,
                            TimeSlotId = 15
                        },
                        new
                        {
                            DayId = 2,
                            TimeSlotId = 16
                        },
                        new
                        {
                            DayId = 2,
                            TimeSlotId = 17
                        },
                        new
                        {
                            DayId = 4,
                            TimeSlotId = 9
                        },
                        new
                        {
                            DayId = 4,
                            TimeSlotId = 10
                        },
                        new
                        {
                            DayId = 4,
                            TimeSlotId = 11
                        },
                        new
                        {
                            DayId = 4,
                            TimeSlotId = 12
                        },
                        new
                        {
                            DayId = 4,
                            TimeSlotId = 13
                        },
                        new
                        {
                            DayId = 4,
                            TimeSlotId = 14
                        },
                        new
                        {
                            DayId = 4,
                            TimeSlotId = 15
                        },
                        new
                        {
                            DayId = 4,
                            TimeSlotId = 16
                        },
                        new
                        {
                            DayId = 4,
                            TimeSlotId = 17
                        },
                        new
                        {
                            DayId = 6,
                            TimeSlotId = 9
                        },
                        new
                        {
                            DayId = 6,
                            TimeSlotId = 10
                        },
                        new
                        {
                            DayId = 6,
                            TimeSlotId = 11
                        },
                        new
                        {
                            DayId = 6,
                            TimeSlotId = 12
                        },
                        new
                        {
                            DayId = 6,
                            TimeSlotId = 13
                        },
                        new
                        {
                            DayId = 6,
                            TimeSlotId = 14
                        },
                        new
                        {
                            DayId = 6,
                            TimeSlotId = 15
                        },
                        new
                        {
                            DayId = 6,
                            TimeSlotId = 16
                        },
                        new
                        {
                            DayId = 6,
                            TimeSlotId = 17
                        });
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.Enrollment", b =>
                {
                    b.Property<int>("CourseReferenceNumber")
                        .HasColumnType("integer");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.HasKey("CourseReferenceNumber", "StudentId");

                    b.HasIndex("StudentId");

                    b.ToTable("Enrollment");

                    b.HasData(
                        new
                        {
                            CourseReferenceNumber = 57494,
                            StudentId = 1L
                        },
                        new
                        {
                            CourseReferenceNumber = 57494,
                            StudentId = 2L
                        },
                        new
                        {
                            CourseReferenceNumber = 57494,
                            StudentId = 3L
                        });
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Normal"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Super Admin"
                        });
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Season");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Spring"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Summer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fall"
                        });
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.Semester", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("SeasonId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("Year", "SeasonId")
                        .IsUnique();

                    b.ToTable("Semester");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndDate = new DateTime(2010, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = 1,
                            StartDate = new DateTime(2010, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Year = 2010
                        },
                        new
                        {
                            Id = 2,
                            EndDate = new DateTime(2010, 8, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = 2,
                            StartDate = new DateTime(2010, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Year = 2010
                        },
                        new
                        {
                            Id = 3,
                            EndDate = new DateTime(2010, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SeasonId = 3,
                            StartDate = new DateTime(2010, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Year = 2010
                        });
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Abbreviation")
                        .HasColumnType("character varying(3)")
                        .HasMaxLength(3);

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Abbreviation")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Subject");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "MAT",
                            Name = "Mathematics"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "HIS",
                            Name = "History"
                        });
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("StartTime", "EndTime")
                        .IsUnique();

                    b.ToTable("TimeSlot");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EndTime = new TimeSpan(0, 8, 45, 0, 0),
                            StartTime = new TimeSpan(0, 7, 30, 0, 0)
                        },
                        new
                        {
                            Id = 2,
                            EndTime = new TimeSpan(0, 10, 15, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 3,
                            EndTime = new TimeSpan(0, 12, 45, 0, 0),
                            StartTime = new TimeSpan(0, 11, 30, 0, 0)
                        },
                        new
                        {
                            Id = 4,
                            EndTime = new TimeSpan(0, 14, 15, 0, 0),
                            StartTime = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            Id = 5,
                            EndTime = new TimeSpan(0, 15, 45, 0, 0),
                            StartTime = new TimeSpan(0, 14, 30, 0, 0)
                        },
                        new
                        {
                            Id = 6,
                            EndTime = new TimeSpan(0, 17, 15, 0, 0),
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 7,
                            EndTime = new TimeSpan(0, 18, 45, 0, 0),
                            StartTime = new TimeSpan(0, 17, 30, 0, 0)
                        },
                        new
                        {
                            Id = 8,
                            EndTime = new TimeSpan(0, 20, 15, 0, 0),
                            StartTime = new TimeSpan(0, 19, 0, 0, 0)
                        },
                        new
                        {
                            Id = 9,
                            EndTime = new TimeSpan(0, 9, 50, 0, 0),
                            StartTime = new TimeSpan(0, 9, 0, 0, 0)
                        },
                        new
                        {
                            Id = 10,
                            EndTime = new TimeSpan(0, 10, 50, 0, 0),
                            StartTime = new TimeSpan(0, 10, 0, 0, 0)
                        },
                        new
                        {
                            Id = 11,
                            EndTime = new TimeSpan(0, 11, 50, 0, 0),
                            StartTime = new TimeSpan(0, 11, 0, 0, 0)
                        },
                        new
                        {
                            Id = 12,
                            EndTime = new TimeSpan(0, 12, 50, 0, 0),
                            StartTime = new TimeSpan(0, 12, 0, 0, 0)
                        },
                        new
                        {
                            Id = 13,
                            EndTime = new TimeSpan(0, 13, 50, 0, 0),
                            StartTime = new TimeSpan(0, 13, 0, 0, 0)
                        },
                        new
                        {
                            Id = 14,
                            EndTime = new TimeSpan(0, 14, 50, 0, 0),
                            StartTime = new TimeSpan(0, 14, 0, 0, 0)
                        },
                        new
                        {
                            Id = 15,
                            EndTime = new TimeSpan(0, 15, 50, 0, 0),
                            StartTime = new TimeSpan(0, 15, 0, 0, 0)
                        },
                        new
                        {
                            Id = 16,
                            EndTime = new TimeSpan(0, 16, 50, 0, 0),
                            StartTime = new TimeSpan(0, 16, 0, 0, 0)
                        },
                        new
                        {
                            Id = 17,
                            EndTime = new TimeSpan(0, 17, 50, 0, 0),
                            StartTime = new TimeSpan(0, 17, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("AbcId")
                        .HasColumnType("character varying(6)")
                        .HasMaxLength(6);

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AbcId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            AbcId = "jvs374",
                            Email = "billBob@example.com",
                            FirstName = "Bill",
                            LastName = "Bob",
                            Password = "password",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2L,
                            AbcId = "cwo479",
                            Email = "chrisRob@example.com",
                            FirstName = "Christopher",
                            LastName = "Rob",
                            Password = "password",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 3L,
                            AbcId = "mji389",
                            Email = "matty@example.com",
                            FirstName = "Matt",
                            LastName = "More",
                            Password = "password",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 4L,
                            AbcId = "fjo342",
                            Email = "sal@example.com",
                            FirstName = "Sally",
                            LastName = "Eddy",
                            Password = "password",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.Classroom", b =>
                {
                    b.HasOne("RamblerAcademyAPI.Models.Building", "Building")
                        .WithMany("Classrooms")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.Course", b =>
                {
                    b.HasOne("RamblerAcademyAPI.Models.Subject", "Subject")
                        .WithMany("Courses")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.CourseSection", b =>
                {
                    b.HasOne("RamblerAcademyAPI.Models.Classroom", "Classroom")
                        .WithMany()
                        .HasForeignKey("ClassroomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RamblerAcademyAPI.Models.Course", "Course")
                        .WithMany("CourseSections")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RamblerAcademyAPI.Models.Semester", "Semester")
                        .WithMany("CourseSections")
                        .HasForeignKey("SemesterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.CourseSectionDayTimeSlot", b =>
                {
                    b.HasOne("RamblerAcademyAPI.Models.CourseSection", "CourseSection")
                        .WithMany("CourseSectionDayTimeSlots")
                        .HasForeignKey("CourseReferenceNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RamblerAcademyAPI.Models.DayTimeSlot", "DayTimeSlot")
                        .WithMany("CourseSectionTimeSlots")
                        .HasForeignKey("DayId", "TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.DayTimeSlot", b =>
                {
                    b.HasOne("RamblerAcademyAPI.Models.Day", "Day")
                        .WithMany()
                        .HasForeignKey("DayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RamblerAcademyAPI.Models.TimeSlot", "TimeSlot")
                        .WithMany("DayTimeSlots")
                        .HasForeignKey("TimeSlotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.Enrollment", b =>
                {
                    b.HasOne("RamblerAcademyAPI.Models.CourseSection", "CourseSection")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseReferenceNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RamblerAcademyAPI.Models.User", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.Semester", b =>
                {
                    b.HasOne("RamblerAcademyAPI.Models.Season", "Season")
                        .WithMany("Semesters")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("RamblerAcademyAPI.Models.User", b =>
                {
                    b.HasOne("RamblerAcademyAPI.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
